### ISSUE TITLE
Horizontal Scroll

### ISSUE THREAD

**Issue by ayush29feb** [dubhacks/16f#1]
I think you are developing in a higher resolution display. I have a horizontal scroll on my laptop.
![image](https://cloud.githubusercontent.com/assets/8674376/15989626/adf5dc14-3030-11e6-8bf1-cb72d2c97e9a.png)

**Comment by cedric2018** [comment]
Oh wow. Yeah the clouds don't even seem to be appearing...hm. But also, there is a horizontal scroll that I haven't fixed yet. Need to figure how to prevent that overflow.
