### ISSUE TITLE
Meet the Team - Navbar

### ISSUE THREAD

**Issue by cedric2018** [dubhacks/16f#25]
In the navbar in Meet the Team page, "Sponsors" is a link and shouldn't be there.

**Comment by mahirk** [comment]
Closed with 46b98f

**Comment by mahirk** [comment]
46b98fac04bd89748e1345987b3691ff26625f27

**Comment by mahirk** [comment]
Closed with 46b98fac04bd89748e1345987b3691ff26625f27

**Comment by mahirk** [comment]
Closed with 46b98fac04bd89748e1345987b3691ff26625f27
