### ISSUE TITLE
Make Responsive

### ISSUE THREAD

**Issue by ayush29feb** [dubhacks/16f#3]
- [ ] Currently the website is not at all responsive.

# Testing (2 Ways)
1. I advice to just use the chrome mobile inspector
2. Host a simple python server and run it on mobile by following the steps below.

Use `python -m SimpleHTTPServer 5000` to start the server. To view on computer just goto `localhost:5000`. However to view on mobile you need to get the IP address of your computer, which can be found here
![image](https://cloud.githubusercontent.com/assets/8674376/15995236/88ca4ba4-30cc-11e6-8c82-dade8f015bdb.png)

Then on your phone go to that IP address URL. for me it was `192.168.1.183:5000`. Yours might be different

**Comment by grant** [comment]
You can also use [ngrok](https://ngrok.com/) (free) to tunnel your localhost to a publicly available unique url. That's what I did for testing various devices last time. Check it out if your curious.
