### ISSUE TITLE
Center date info

### ISSUE THREAD

**Issue by NavidAzodi** [dubhacks/16f#37]
## Overview of Problem:

<img width="273" alt="screen shot 2016-08-16 at 11 10 25 pm" src="https://cloud.githubusercontent.com/assets/11811544/17726368/741a1b8a-6407-11e6-812d-cc93f57cd1a1.png">

Center the date box information

**Comment by ayush29feb** [comment]
fixed
![image](https://cloud.githubusercontent.com/assets/8674376/17726451/e797f58c-6407-11e6-9173-82b6292860a0.png)
