### ISSUE TITLE
Mission Section Issues

### ISSUE THREAD

**Issue by eyeshoe** [dubhacks/16f#44]
## Overview of Problem:

In mission statement, change the words (believe, connect, build) in black, to the pink color to emphasize them
Instead of each “We” statement in a line, put it in a box/circle or just put each in a single line. They are placed poorly and lose impact. Consistency/look of them is off.
Overall, make each section/word more separated. Each word need to be a distinctive section

**Comment by ayush29feb** [comment]
can you send a pull request for this? Its a pretty small fix. Maybe just push it in `gh-pages` directly
