### ISSUE TITLE
Bottom Section Issues

### ISSUE THREAD

**Issue by eyeshoe** [dubhacks/16f#47]
## Overview of Problem:
- [x] Remove extra 3 social media icons on the left. Replace with date box from top of page
- [x] “Our Team” should not turn white and bump up. Give it the same look/function as “Apply” and    “Sponsor” at the top of the website
- [ ] Shrink this entire section. There is no need for the skyline to be so big
- [x] Bottom of page: change white strip to a pink stripe with white text

**Comment by ayush29feb** [comment]
are the checked to-do's finished? can you send a pull request?
