### ISSUE TITLE
Our Team page issues

### ISSUE THREAD

**Issue by eyeshoe** [dubhacks/16f#48]
## Overview of Problem:

Fix the hover/loading. Just apply a B/W filter when hover, not a separate image. It seems the extra image is slowing it down
Having a completely extra page for our team is very confusing. A lot of people have given me feedback on this and say we should integrate into a single page, not two.
         After “Sponsors” section, put a pink bar with “Our Team”
         Put our photos underneath that pink bar
         After our photos, put pink/orange Seattle skyline section
         Remove “Our Team” button from the skyline section

**Comment by ayush29feb** [comment]
I thought someone was working on this? Don't we already have a fix ready?
