### ISSUE TITLE
Sponsor Doc

### ISSUE THREAD

**Issue by grant** [dubhacks/16f#6]
You may want to add the sponsor doc to 

`http://16f.dubhacks.co/sponsor.pdf`

Like done in:
`http://15f.dubhacks.co/sponsor.pdf`
`http://14f.dubhacks.co/sponsor.pdf`

Just add a `sponsor.pdf` to the root directory of the `gh-pages` branch.
I would also make `gh-pages` the default branch of this repo.

@mahirk

**Comment by mahirk** [comment]
@grant we are still designing the doc :)
